ica/views/management.py
import math

from flask import (
    Blueprint, render_template, request, redirect, flash, url_for
)
from flask_login import login_required, current_user
from mongoengine.errors import ValidationError

from ica.models.user import User
from ica.models.announcement import Announcement
from ica.models.event import Event
from ica.forms import DatabaseEditForm, AnnouncementForm, EventForm
from ica.utils import admin_required, generate_event_code

management = Blueprint('management', __name__,
                       template_folder='management')


@management.route('/', methods=['GET'])
@login_required
@admin_required
def index():
    return render_template('management/index.html', **{
        'user': current_user
    })


@management.route('/edit', methods=['GET', 'POST'])
@login_required
@admin_required
def edit():
    members = User.objects.only('fname', 'lname', 'year', 'pfpic_url')
    return render_template('management/edit.html', **{
        'user': current_user,
        'members': members.order_by('fname')
    })


@management.route('/edit_user/<string:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_user(user_id):
    try:
        focus = User.objects(id=user_id).first()
        form = DatabaseEditForm(request.form)
        if request.method == 'POST' and form.validate():
            if form.fname.data:
                focus.update(set__fname=form.fname.data)
            if form.lname.data:
                focus.update(set__lname=form.lname.data)
            if form.email.data:
                focus.update(set__email=form.email.data)
            if form.hometown.data:
                focus.update(set__hometown=form.hometown.data)
            if form.major.data:
                focus.update(set__major=form.major.data)
            if form.year.data:
                focus.update(set__year=form.year.data)
            if form.points.data:
                focus.update(set__points=form.points.data)
            if form.board_member.data:
                focus.update(set__board_member=form.board_member.data)
            if form.general_member.data:
                focus.update(set__general_member=form.general_member.data)
            if form.active_member.data:
                focus.update(set__active_member=form.active_member.data)
            if form.spotlight.data:
                focus.update(set__spotlight=form.spotlight.data)
            flash('{} {}\'s profile was updated'.format(
                focus.fname, focus.lname
            ))
            return redirect(url_for('management.edit_user',
                                    user_id=user_id))

    except ValidationError:
        focus = None
    return render_template('management/edit_user.html', **{
        'user': current_user,
        'focus': focus,
        'form': form
    })


@management.route('/points', methods=['GET', 'POST'])
@login_required
@admin_required
def points():
    return render_template('management/points.html', **{
        'user': current_user
    })


@management.route('/announcements', methods=['GET', 'POST'])
@login_required
@admin_required
def announcements():
    fields = ['message', 'creation_date']
    msgs = Announcement.objects(author=current_user.id).only(
        *fields
    ).order_by('creation_date').select_related()
    form = AnnouncementForm(request.form)
    if request.method == 'POST' and form.validate():
        announcement = Announcement(
            author=current_user.id,
            message=form.text.data
        )
        announcement.save()
        flash('Your announcement was posted on the overview page!')
        return redirect(url_for('management.announcements'))
    return render_template('management/announcements.html', **{
        'user': current_user,
        'msgs': msgs,
        'form': form
    })


@management.route('/events', methods=['GET', 'POST'])
@login_required
@admin_required
def events():
    fields = ['name', 'datetime', 'location', 'pts', 'code', 'attended']
    events = Event.objects(author=current_user.id).only(
        *fields
    ).order_by('datetime').select_related()
    form = EventForm(request.form)
    if request.method == 'POST' and form.validate():
        fields = {
            'name': form.name.data,
            'datetime': form.datetime.data,
            'location': form.location.data,
            'description': form.description.data,
            'pts': math.ceil(form.pts.data),
            'author': current_user.id,
            'code': generate_event_code()
        }

        if form.fb_link.data:
            fields.update({'fb_link': form.fb_link.data})

        event = Event(**fields)
        event.save()

        flash('This announcement will show up on the' +
              ' member overview page.')
        return redirect(url_for('management.events'))
    return render_template('management/events.html', **{
        'user': current_user,
        'events': events,
        'form': form
    })

ica/views/social.py
import datetime

from flask import Blueprint, render_template, redirect, request, flash, url_for, abort
from flask_login import login_required, current_user

from ica.models.user import User
from ica.models.announcement import Announcement
from ica.models.event import Event
from ica.forms import ProfileForm, SearchForm, CheckInForm
from ica.utils import (
    get_file_extension, allowed_filename, upload_photo, get_recommended_users
)
from ica.logger import client
from ica.tasks import low_queue, high_queue

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])
UPLOAD_FOLDER = 'tmp'

social = Blueprint('social', __name__, template_folder='templates')


@social.route('/', methods=['GET'])
@login_required
def index():
    # Get top 5 most recent announcements
    msgs_fields = ['author', 'message', 'creation_date']
    msgs = Announcement.objects.only(
        *msgs_fields
    ).order_by('-creation_date').select_related()[:5]

    # Get upcoming events
    events_fields = ['name', 'datetime', 'location', 'description',
                     'pts', 'fb_link']
    events = Event.objects.only(
        *events_fields
    ).order_by('-creation_date').select_related()

    # Filter events based on their time - if it is upcoming relative
    # to today's date, then it is included
    events = [event for event in events if
              event.datetime > datetime.datetime.now()]

    return render_template('social/index.html', **{
        'user': current_user,
        'msgs': msgs,
        'events': events
    })


@social.route('/members', methods=['GET', 'POST'])
@login_required
def members():
    member_set = None
    recommended = get_recommended_users(current_user)
    search_form = SearchForm(request.form)
    if request.method == 'POST' and search_form.validate():
        query = search_form.query.data
        fields = ['fname', 'lname', 'year', 'hometown', 'pfpic_url']
        member_set = User.objects.only(*fields).search_text(
            query
        ).order_by('fname').filter(id__ne=current_user.id)

        low_queue.enqueue(
            client.log_event,
            request.headers.get('X-Forwarded-For', request.remote_addr),
            '{} {} searched for \'{}\''.format(current_user.fname,
                                               current_user.lname,
                                               query)
        )

    return render_template('social/members.html', **{
        'user': current_user,
        'search_form': search_form,
        'recommended': recommended,
        'members': member_set
    })


@social.route('/leaderboard', methods=['GET'])
@login_required
def leaderboard():
    fields = ['fname', 'lname', 'pfpic_url', 'year', 'points']
    leaderboard = User.objects.only(*fields).order_by('-points')[:10]
    leaderboard = [user for user in leaderboard if user.points > 0 and not user.board_member]
    return render_template('social/leaderboard.html', **{
        'user': current_user,
        'leaderboard': leaderboard
    })


@social.route('/followers', methods=['GET'])
@login_required
def followers():
    fields = ['fname', 'lname', 'year', 'email', 'pfpic_url']
    followers = User.objects(following=current_user.id).only(
        *fields
    ).order_by('fname')
    return render_template('social/followers.html', **{
        'user': current_user,
        'followers': followers
    })


@social.route('/checkin', methods=['GET', 'POST'])
@login_required
def checkin():
    checkin_form = CheckInForm(request.form)
    context = {
        'user': current_user,
        'checkin_form': checkin_form
    }

    if request.method == 'POST' and checkin_form.validate():
        code = checkin_form.code.data

        # Get event correpsonding to that code
        fields = ['code', 'name', 'pts']
        events = Event.objects(code=code).only(*fields)

        if not events:
            # Event does not exist
            msg_type = 'negative'
            header = 'There was a problem in your request.'
            flash('Sorry, this event does not exist.', 'error')
        else:
            # Update the event attended list and update
            # the user's points with event's points
            event = events.first()
            event.update(add_to_set__attended=current_user.id)
            user = User.objects(id=current_user.id).only(*['id'])
            user.update(inc__points=event.pts)

            msg_type = 'positive'
            header = 'Your points were recorded!'
            flash('You received {} points for {}!'.format(
                event.pts, event.name
            ))

        context.update({
            'msg_type': msg_type,
            'header': header
        })

    return render_template('social/checkin.html', **context)


@social.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    profile_form = ProfileForm(request.form)
    if request.method == 'POST' and profile_form.validate():
        if profile_form.bio.data:
            current_user.update(set__bio=profile_form.bio.data)
        if profile_form.hometown.data:
            current_user.update(set__hometown=profile_form.hometown.data)
        if profile_form.major.data:
            current_user.update(set__major=profile_form.major.data)
        if profile_form.year.data:
            current_user.update(set__year=profile_form.year.data)
        flash('Your profile was successfully updated!', 'success')
        return redirect(url_for('social.settings'))
    return render_template('social/settings.html', **{
        'user': current_user,
        'profile_form': profile_form
    })


@social.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_pfpic():
    if request.method == 'POST':
        # Check if request has the file part
        if 'file' not in request.files:
            flash('File not included in request', 'error')
            return redirect(url_for('social.settings'))

        # If user does not select a file, browser must also
        # submit an empty part without file part
        pic = request._get_current_object().files['file']
        if pic.filename == '':
            flash('You have not selected a picture to upload.', 'error')
            return redirect(url_for('social.settings'))

        if not allowed_filename(pic.filename, ALLOWED_EXTENSIONS):
            flash('You selected an incorrect file type. Only ' +
                  ' png, jpg, jpeg, and gif types are allowed.', 'error')
            return redirect(url_for('social.settings'))

        cl = request.content_length
        if cl is not None and cl > 0.5 * 1024 * 1024:
            flash('Size of profile picture must be less than 500 KB.', 'error')
            return redirect(url_for('social.settings'))

        if pic and allowed_filename(pic.filename, ALLOWED_EXTENSIONS):
            # Generate unique picture token
            ext = get_file_extension(pic.filename)
            filename = '{}.{}'.format(current_user.id, ext)

            # Get time at which pictuer was uploaded
            # %H%M%S - Hour-Minute-Seconds
            time = datetime.datetime.now().strftime('%H%M%S')

            # Set profile picture URL
            bucket_name = 'icadevelopment'
            link = 'https://s3.us-east-2.amazonaws.com/' + bucket_name + \
                   '/{}-{}'.format(time, filename)
            current_user.update(set__pfpic_url=link)

            # Complete task asynchronously
            high_queue.enqueue(upload_photo, pic.read(), filename,
                               time, current_user.id)

            flash('Your picture will be uploaded momentarily!', 'success')
            return redirect(url_for('social.settings'))


@social.route('/follow/<string:user_id>', methods=['GET'])
@login_required
def follow_member(user_id):
    """DEPRECATED - use the /follow API endpoint"""

    user_b = User.objects(id=user_id).only('id').first()
    if user_b:
        user_a = User.objects(id=current_user.id).only('id').first()
        if user_b.id != user_a.id:
            user_a.update(add_to_set__following=user_b)
            user_b.update(add_to_set__followers=user_a)

            low_queue.enqueue(
                client.log_event,
                request.headers.get('X-Forwarded-For', request.remote_addr),
                '{} {} followed {} {}'.format(user_a.fname, user_a.lname,
                                              user_b.fname, user_b.lname)
            )
    return redirect(url_for('social.followers'))


@social.route('/unfollow/<string:user_id>', methods=['GET'])
@login_required
def unfollow_member(user_id):
    """DEPRECATED - use the /unfollow API endpoint"""
    user_b = User.objects(id=user_id).only('id').first()
    if user_b:
        user_a = User.objects(id=current_user.id).only('id').first()
        user_a.update(pull__following=user_b)
        user_b.update(pull__followers=user_a)

        low_queue.enqueue(
            client.log_event,
            request.headers.get('X-Forwarded-For', request.remote_addr),
            '{} {} unfollowed {} {}'.format(user_a.fname, user_a.lname,
                                            user_b.fname, user_b.lname)
        )
    return redirect(url_for('social.followers'))

ica/templates/social/checkin.html
{% extends "social/layout.html" %}
{% from "macros.html" import render_success, render_error %}
{% from "social/macros.html" import render_event %}

{% block title %}ICA - Check In{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="ui small {{ msg_type }} message">
            <i class="close icon"></i>
            <div class="header">{{ header }}</div>
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}
<div id="checkin">
    <h3>Check In by Unique Code</h3>
    <form class="ui form" action="{{ url_for('social.checkin') }}" method="POST">
        {{ checkin_form.csrf_token }}
        <div class="two fields">
            {{ checkin_form.code }}
            <button class="ui button" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

ica/templates/social/followers.html
{% extends "social/layout.html" %}
{% from "social/macros.html" import render_event %}

{% block nav_followers %}<a class="active item" href="{{ url_for('social.followers') }}">Followers</a>{% endblock %}

{% block title %}ICA - Followers{% endblock %}

{% block content %}
<div id="followers" class="ui middle aligned divided list">
    {% if followers %}
    {% for follower in followers %}
    <div class="item">
        <div class="right floated content">
            {% if user.is_following(follower) %}
            <button class="ui basic tiny red button follow" user="{{ follower.id }}">Unfollow</button>
            {% else %}
            <button class="ui basic tiny green button follow" user="{{ follower.id }}">Follow</button>
            {% endif %}
        </div>
        <img class="ui mini rounded middle aligned image" src="{{ follower.get_pfpic() }}">
        <div class="content">
            <h4 class="header">{{ follower.fname }} {{ follower.lname }}</h4>
            <div class="description">{{ follower.year }}</div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>You have no followers!</p>
    {% endif %}
</div>
{% endblock %}

ica/templates/social/index.html
{% extends "social/layout.html" %}
{% from "social/macros.html" import render_event %}

{% block title %}ICA - Social{% endblock %}

{% block nav_overview %}<a class="active item" href="{{ url_for('social.index') }}">Overview</a>{% endblock %}

{% block content %}
<h3 class="ui header">Announcements</h3>
<div id="announcements">
    {% if msgs %}
    <div class="ui feed">
        {% for msg in msgs %}
        <div class="event">
            <div class="label">
                <img src="{{ msg.author.get_pfpic() }}">
            </div>
            <div class="content">
                <div class="summary">
                    <a data-tooltip="{{ msg.author.fname }} {{ msg.author.lname }} - {{ msg.author.major }} - {{ msg.author.year }}" data-position="top left" class="user">{{ msg.author.fname }} {{ msg.author.lname }}</a>
                    <div class="date">{{ msg.creation_date.strftime('%m/%d') }}</div>
                </div>
                <div class="extra text">{{ msg.message }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>There are no announcements.</p>
    {% endif %}
</div>

<h3 class="ui header">Upcoming Events</h3>
<div id="events">
    {% if events %}
    <div class="ui stackable grid">
        {% for event in events %}
        <div class="eight wide column">
            <div class="ui fluid card">
                <div class="content">
                    <div class="header">{{ event.name }}</div>
                    <div class="meta">
                        <span>{{ event.datetime.strftime('%m/%d') }} @ {{ event.location }}</span>
                    </div>
                    <p>{{ event.description|truncate(150) }} {% if event.fb_link %}<a href="{{ event.fb_link }}">See More</a>{% endif %}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>There are no upcoming events.</p>
    {% endif %}
</div>
{% endblock %}

ica/templates/social/layout.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/social.css') }}">
{% endblock %}

{% block app %}
<!-- Profile and Subnavigation -->
<div id="profile" class="ui centered stackable grid">
    <div class="three wide column">
        <div class="ui left aligned container">
            <img class="ui centered fluid rounded image" src="{{ user.get_pfpic() }}">

            <h1>{{ user.fname }} {{ user.lname }}</h1>

            {% if user.bio %}
                <p>{{ user.bio }}</p>
            {% endif %}

            <div class="ui divider"></div>

            <div class="ui list">
                <div class="item">
                    <i class="location arrow icon"></i>
                    <div class="content">{{ user.hometown }}</div>
                </div>
                <div class="item">
                    <i class="bookmark icon"></i>
                    <div class="content">{{ user.major }}</div>
                </div>
                <div class="item">
                    <i class="user icon"></i>
                    <div class="content">{{ user.year }}</div>
                </div>
                {% if user.hobbies %}
                <div class="item">
                    <i class="heart icon"></i>
                    <div class="content">{{ users.hobbies|join(', ') }}</div>
                </div>
                {% endif %}
            </div>

            <a class="ui tiny label">{{ user.points }} Events</a>
            {% if user.board_member %}
                <a class="ui tiny label">Board Member</a>
            {% endif %}
            {% if user.spotlight %}
                <a class="ui tiny label">Member of the Week</a>
            {% endif %}
            {% if user.social_comm %}
                <a class="ui tiny label">Social Committee</a>
            {% endif %}
            {% if user.service_comm %}
                <a class="ui tiny label">Service Committee</a>
            {% endif %}
            {% if user.is_top_member(10) %}
                <a class="ui tiny label">Top Member</a>
            {% endif %}
        </div>

    </div>
    <div id="menu" class="ten wide column">
        <div class="ui secondary pointing stackable menu">
            {% block nav_overview %}<a class="item" href="{{ url_for('social.index') }}">Overview</a>{% endblock %}
            {% block nav_members %}<a class="item" href="{{ url_for('social.members') }}">Members</a>{% endblock %}
            {% block nav_leaderboard %}<a class="item" href="{{ url_for('social.leaderboard') }}">Leaderboard</a>{% endblock %}
            {% block nav_followers %}<a class="item" href="{{ url_for('social.followers') }}">Followers</a>{% endblock %}
            <div id="nav-apps" class="ui dropdown item">
                Apps <i class="dropdown icon"></i>
                <div class="menu">
                    <a class="item" href="{{ url_for('social.checkin') }}">Check In</a>
                    {% if user.board_member %}<a class="item" href="{{ url_for('management.index') }}">Management</a>{% endif %}
                </div>
            </div>
        </div>
        {% block content %}{% endblock %}
    </div>
</div>
{% endblock %}

ica/templates/social/leaderboard.html
{% extends "social/layout.html" %}
{% from "social/macros.html" import render_event %}

{% block nav_leaderboard %}<a class="active item" href="{{ url_for('social.leaderboard') }}">Leaderboard</a>{% endblock %}

{% block title %}ICA - Leaderboard{% endblock %}

{% block content %}
<table id="leaderboard" class="ui celled table">
    <thead>
        <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Events</th>
        </tr>
    </thead>
    <tbody>
        {% for member in leaderboard %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <h4 class="ui image header">
                    <img class="ui mini rounded image" src="{{ member.get_pfpic() }}">
                    <div class="content">
                        {{ member.fname }} {{ member.lname }}
                        <div class="sub header">{{ member.year }}</div>
                    </div>
                </h4>
            </td>
            <td>{{ member.points }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

ica/templates/social/macros.html
{% macro render_event(name, date, location, text) %}
<div class="eight wide column">
    <div class="ui fluid card">
        <div class="content">
            <div class="header">{{ name }}</div>
            <div class="meta">
                <span>{{ date }}</span>
                <span>{{ location }}</span>
            </div>
            <p>{{ text }}</p>
        </div>
    </div>
</div>
{% endmacro %}

{% macro render_field(field, verbose) %}
<div class="field">
    <label>{{ field.label }}</label>
    {{ field(**kwargs)|safe }}
</div>
{% if field.errors %}
    <div class="ui error message">
        <ul class="list">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
{% endmacro %}

ica/templates/social/members.html
{% extends "social/layout.html" %}

{% block nav_members %}<a class="active item" href="{{ url_for('social.members') }}">Members</a>{% endblock %}

{% block title %}ICA - Members{% endblock %}

{% block content %}
<h3>Pay Membership Dues</h3>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="T7JB9NCKLE4G8">
<table>
<tr></tr><tr><td><select name="os0">
	<option value="Year">Year $20.91 USD</option>
	<option value="Semester">Semester $15.76 USD</option>
	<option value="Test">Test $0.00 USD</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
<br>
<p>Please fill out the <a href="https://docs.google.com/forms/u/1/d/1f94YiqfUddQpuwR1jfmeRgoBIFtEMxAGciXYQdQYE9c/edit" target="_blank">ICA Membership form</a> after paying membership dues.</p>

<h3>Recommended to Follow</h3>
{% if recommended %}
<div id="recommended" class="ui four column stackable doubling grid">
    {% for member in recommended %}
    <div class="column">
        <div class="ui card">
            <div class="image">
                <img src="{{ member.get_pfpic() }}">
            </div>
            <div class="content">
                <a class="header">{{ member.fname }} {{ member.lname }}</a>
                <div class="description">
                    <p>{{ member.year }}<br>{{ member.hometown }}</p>
                </div>
                <div class="extra content">
                    {% if user.is_following(member) %}
                    <button class="ui basic tiny red button follow" user="{{ member.id }}">Unfollow</button>
                    {% else %}
                    <button class="ui basic tiny green button follow" user="{{ member.id }}">Follow</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>Follow some members to get suggestions!</p>
{% endif %}

<h3>Search for users</h3>
<form id="search" class="ui form" action="{{ url_for('social.members') }}" method="POST">
    {{ search_form.csrf_token }}
    <div class="two fields">
        {{ search_form.query }}
        <button class="ui button" type="submit">Search</button>
    </div>
</form>

{% if members %}
<div id="members" class="ui four column stackable doubling grid">
    {% for member in members %}
    <div class="column">
        <div class="ui card">
            <div class="image">
                <img src="{{ member.get_pfpic() }}">
            </div>
            <div class="content">
                <a class="header">{{ member.fname }} {{ member.lname }}</a>
                <div class="description">
                    <p>{{ member.year }}<br>{{ member.hometown }}</p>
                </div>
                <div class="extra content">
                    {% if user.is_following(member) %}
                    <button class="ui basic tiny red button follow" user="{{ member.id }}">Unfollow</button>
                    {% else %}
                    <button class="ui basic tiny green button follow" user="{{ member.id }}">Follow</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

ica/templates/social/settings.html
{% extends "social/layout.html" %}
{% from "social/macros.html" import render_event, render_field %}

{% block title %}ICA - Settings{% endblock %}

{% block content %}

{% with messages = get_flashed_messages(category_filter=["success"]) %}
    {% if messages %}
    <div class="ui success message">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}

{% with messages = get_flashed_messages(category_filter=["error"]) %}
    {% if messages %}
    <div class="ui error message">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}

<div class="ui container">
    <div class="ui stackable grid">
        <div class="ten wide column">
            <h3>Profile Settings</h3>
            <form class="ui form" action="{{ url_for('social.settings') }}" method="POST">
                {{ profile_form.csrf_token }}
                {{ render_field(profile_form.bio, placeholder=current_user.bio) }}
                {{ render_field(profile_form.hometown, placeholder=current_user.hometown) }}
                {{ render_field(profile_form.major, placeholder=current_user.major) }}
                {{ render_field(profile_form.year) }}
                <button class="ui button" type="submit">Update Profile</button>
            </form>
        </div>
        <div class="six wide column">
            <h3>Profile picture</h3>
            <img class="ui small rounded image" src="{{ user.get_pfpic() }}">
            <form id="upload" action="{{ url_for('social.upload_pfpic') }}" method="POST" enctype="multipart/form-data">
                <input type="file" name="file"><br>
                <button class="ui button" type="submit">Upload New Picture</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}