ica/models/announcement.py
import datetime

from mongoengine import (
    Document, StringField, DateTimeField,
    ReferenceField, ListField
)

from ica.models.user import User


class Announcement(Document):
    """
    Announcement that appears on the ICA social
    network dashboard
    """

    # Author of the announcement (this needs
    # to be a board member)
    author = ReferenceField(User, required=True)

    # Announcement text
    message = StringField(required=True)

    # When the announcement was created
    creation_date = DateTimeField(default=datetime.datetime.now)

    # Users that like the announcement
    likes = ListField(ReferenceField(User))

    def __repr__(self):
        return 'Announcement<{}, {}>'.format(
            self.author, self.message
        )

    def to_dict(self):
        author = '{} {}'.format(self.author.fname, self.author.lname)

        return {
            'author': author,
            'message': self.message,
            'likes': str(self.likes)
        }

ica/models/event.py
from mongoengine import (
    Document, StringField, IntField, DateTimeField,
    ListField, ReferenceField
)

from ica.models.user import User


class Event(Document):

    # Name of the event
    name = StringField(required=True)

    # Date and time event is being held
    # Format: %Y-%m-%d (time isn't used)
    datetime = DateTimeField(required=True)

    # Where the event is taking place
    location = StringField(required=True)

    # Description of event - most likely copy/pasted
    # from its Facebook description
    description = StringField(required=True)

    # Points per hour for members
    pts = IntField(min_value=0, required=True)

    # Link to QR code
    qr_code = StringField()

    # Unique event code
    code = StringField()

    # Link to Facebook event - might not be relevant for
    # ad-hoc events like 'Flash Study Hours'
    fb_link = StringField()

    # Board member in charge of the event
    author = ReferenceField(User)

    # Members that attended the event
    attended = ListField(ReferenceField(User))

    def __repr__(self):
        return 'Event<{}>'.format(self.name)

    def to_dict(self):
        author = self.author.to_dict()
        attended = [user.to_dict() for user in self.attended]

        return {
            'name': self.name,
            'datetime': self.datetime,
            'location': self.location,
            'description': self.description,
            'pts': str(self.pts),
            'fb_link': self.fb_link,
            'author': author,
            'attended': attended
        }

ica/views/management.py
import math

from flask import (
    Blueprint, render_template, request, redirect, flash, url_for
)
from flask_login import login_required, current_user
from mongoengine.errors import ValidationError

from ica.models.user import User
from ica.models.announcement import Announcement
from ica.models.event import Event
from ica.forms import DatabaseEditForm, AnnouncementForm, EventForm
from ica.utils import admin_required, generate_event_code

management = Blueprint('management', __name__,
                       template_folder='management')


@management.route('/', methods=['GET'])
@login_required
@admin_required
def index():
    return render_template('management/index.html', **{
        'user': current_user
    })


@management.route('/edit', methods=['GET', 'POST'])
@login_required
@admin_required
def edit():
    members = User.objects.only('fname', 'lname', 'year', 'pfpic_url')
    return render_template('management/edit.html', **{
        'user': current_user,
        'members': members.order_by('fname')
    })


@management.route('/edit_user/<string:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_user(user_id):
    try:
        focus = User.objects(id=user_id).first()
        form = DatabaseEditForm(request.form)
        if request.method == 'POST' and form.validate():
            if form.fname.data:
                focus.update(set__fname=form.fname.data)
            if form.lname.data:
                focus.update(set__lname=form.lname.data)
            if form.email.data:
                focus.update(set__email=form.email.data)
            if form.hometown.data:
                focus.update(set__hometown=form.hometown.data)
            if form.major.data:
                focus.update(set__major=form.major.data)
            if form.year.data:
                focus.update(set__year=form.year.data)
            if form.points.data:
                focus.update(set__points=form.points.data)
            if form.board_member.data:
                focus.update(set__board_member=form.board_member.data)
            if form.general_member.data:
                focus.update(set__general_member=form.general_member.data)
            if form.active_member.data:
                focus.update(set__active_member=form.active_member.data)
            if form.spotlight.data:
                focus.update(set__spotlight=form.spotlight.data)
            flash('{} {}\'s profile was updated'.format(
                focus.fname, focus.lname
            ))
            return redirect(url_for('management.edit_user',
                                    user_id=user_id))

    except ValidationError:
        focus = None
    return render_template('management/edit_user.html', **{
        'user': current_user,
        'focus': focus,
        'form': form
    })


@management.route('/points', methods=['GET', 'POST'])
@login_required
@admin_required
def points():
    return render_template('management/points.html', **{
        'user': current_user
    })


@management.route('/announcements', methods=['GET', 'POST'])
@login_required
@admin_required
def announcements():
    fields = ['message', 'creation_date']
    msgs = Announcement.objects(author=current_user.id).only(
        *fields
    ).order_by('creation_date').select_related()
    form = AnnouncementForm(request.form)
    if request.method == 'POST' and form.validate():
        announcement = Announcement(
            author=current_user.id,
            message=form.text.data
        )
        announcement.save()
        flash('Your announcement was posted on the overview page!')
        return redirect(url_for('management.announcements'))
    return render_template('management/announcements.html', **{
        'user': current_user,
        'msgs': msgs,
        'form': form
    })


@management.route('/events', methods=['GET', 'POST'])
@login_required
@admin_required
def events():
    fields = ['name', 'datetime', 'location', 'pts', 'code', 'attended']
    events = Event.objects(author=current_user.id).only(
        *fields
    ).order_by('datetime').select_related()
    form = EventForm(request.form)
    if request.method == 'POST' and form.validate():
        fields = {
            'name': form.name.data,
            'datetime': form.datetime.data,
            'location': form.location.data,
            'description': form.description.data,
            'pts': math.ceil(form.pts.data),
            'author': current_user.id,
            'code': generate_event_code()
        }

        if form.fb_link.data:
            fields.update({'fb_link': form.fb_link.data})

        event = Event(**fields)
        event.save()

        flash('This announcement will show up on the' +
              ' member overview page.')
        return redirect(url_for('management.events'))
    return render_template('management/events.html', **{
        'user': current_user,
        'events': events,
        'form': form
    })

ica/templates/management/announcements.html
{% extends "management/layout.html" %}
{% from "macros.html" import render_field, render_success %}

{% block content %}
<div class="ui breadcrumb">
    <a class="section" href="{{ url_for('management.index') }}">Management</a>
    <div class="divider"> / </div>
    <a class="section" href="{{ url_for('management.announcements') }}">Announcements</a>
</div>

{{ render_success('Your announcement was successfully posted!') }}

<h3 class="ui header">Your Announcements</h3>

{% if msgs %}
<div class="ui relaxed divided small list">
    {% for msg in msgs %}
    <div class="item">
        <i class="big talk middle aligned icon"></i>
        <div class="content">
            <div class="description">{{ msg.creation_date.strftime('%m/%d/%Y')}} - {{ msg.message }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

<h3 class="ui header">Create an Announcement</h3>
<form class="ui form error" action="{{ url_for('management.announcements') }}" method="POST">
    {{ form.csrf_token }}
    {{ render_field(form.text, True, placeholder="Announcement Message") }}
    <button class="ui button" type="submit">Post Announcement</button>
</form>
{% endblock %}

ica/templates/management/edit.html
{% extends "management/layout.html" %}

{% block content %}
<div class="ui breadcrumb">
    <a class="section" href="{{ url_for('management.index') }}">Management</a>
    <div class="divider"> / </div>
    <a class="section" href="{{ url_for('management.edit') }}">Database</a>
</div>
<div class="ui middle aligned divided list">
    {% for member in members %}
    <div class="item">
        <div class="right floated content">
            <a class="ui basic button" href="{{ url_for('management.edit_user', user_id=member.id) }}">Edit</a>
        </div>
        <img class="ui mini rounded middle aligned image" src="{{ member.get_pfpic() }}">
        <div class="content">
            <h4 class="header">{{ member.fname }} {{ member.lname }}</h4>
            <div class="description">{{ member.year }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

ica/templates/management/edit_user.html
{% extends "management/layout.html" %}
{% from "macros.html" import render_field %}

{% block content %}
{% if focus %}

<div class="ui breadcrumb">
    <a class="section" href="{{ url_for('management.index') }}">Management</a>
    <div class="divider"> / </div>
    <a class="section" href="{{ url_for('management.edit') }}">Database</a>
    <div class="divider"> / </div>
    <a class="section" href="{{ url_for('management.edit_user', user_id=focus.id) }}">{{ focus.fname }} {{ focus.lname }}</a>
</div>

<div class="ui text center aligned container">
    <h2>{{ focus.fname }} {{ focus.lname }}</h2>
    <img class="ui small rounded middle aligned image" src="{{ focus.get_pfpic() }}">
</div>

<div class="ui text container">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="ui positive message">
                <i class="close icon"></i>
                <div class="header">The database was successfully updated!</div>
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    <form class="ui form error" action="{{ url_for('management.edit_user', user_id=focus.id) }}" method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.fname, placeholder=focus.fname) }}
        {{ render_field(form.lname, placeholder=focus.lname) }}
        {{ render_field(form.major, placeholder=focus.major) }}
        {{ render_field(form.year, placeholder=focus.year) }}
        {{ render_field(form.points, placeholder=focus.points) }}
        {{ render_field(form.board_member, placeholder=focus.board_member) }}
        {{ render_field(form.board_position, placeholder=focus.board_position) }}
        {{ render_field(form.general_member, placeholder=focus.general_member) }}
        {{ render_field(form.active_member, placeholder=focus.active_member) }}
        {{ render_field(form.spotlight, placeholder=focus.spotlight) }}
        <button class="ui button" type="submit">Save Changes</button>
    </form>
</div>
{% else %}
<p>Invalid User</p>
{% endif %}
{% endblock %}

ica/templates/management/events.html
{% extends "management/layout.html" %}
{% from "macros.html" import render_field, render_success %}

{% block content %}
<div class="ui breadcrumb">
    <a class="section" href="{{ url_for('management.index') }}">Management</a>
    <div class="divider"> / </div>
    <a class="section" href="{{ url_for('management.events') }}">Events</a>
</div>

{{ render_success("Your event was successfully saved!") }}

<h3 class="ui header">Your Events</h3>
{% if events %}
<div class="ui relaxed divided small list">
    {% for event in events %}
    <div class="item">
        <i class="big checked calendar middle aligned icon"></i>
        <div class="content">
            <p class="header">{{ event.name }} ({{ event.pts }} pts/hr)</p>
            <div class="description">{{ event.datetime.strftime('%m/%d/%Y') }} @ {{ event.location }}, ID: {{ event.code }}, {{ event.attended|length }} Participants</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

<h3 class="ui header">Create an Event</h3>

<form class="ui form error" action="{{ url_for('management.events') }}" method="POST">
    {{ form.csrf_token }}
    {{ render_field(form.name) }}
    {{ render_field(form.datetime, id="event-datepicker") }}
    {{ render_field(form.location) }}
    {{ render_field(form.description) }}
    {{ render_field(form.pts) }}
    {{ render_field(form.fb_link) }}
    <button class="ui button" type="submit">Create Event</button>
</form>

{% endblock %}

ica/templates/management/index.html
{% extends "management/layout.html" %}

{% block title %}ICA - Management{% endblock %}

{% block content %}
<h1 id="title" class="ui center aligned header">
    Management
    <div class="sub header">Administration dashboard for ICA board members</div>
</h1>

<div id="apps" class="ui container">
    <div class="ui left aligned stackable three column grid">
        <div class="column">
            <h3 class="ui center aligned icon header">
                <i class="database icon"></i>
                <a href="{{ url_for('management.edit') }}">Database</a>
            </h3>
            <p>Edit the database for various items by searching for users</p>
        </div>
        <div class="column">
            <h3 class="ui center aligned icon header">
                <i class="add to calendar icon"></i>
                <a href="{{ url_for('management.events') }}">Events</a>
            </h3>
            <p>Create a public event for the social network</p>
        </div>
        <div class="column">
            <h3 class="ui center aligned icon header">
                <i class="announcement icon"></i>
                <a href="{{ url_for('management.announcements') }}">Announcements</a>
            </h3>
            <p>Create an announcement for the social network</p>
        </div>
    </div>
</div>
{% endblock %}

ica/templates/management/layout.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/management.css') }}">
{% endblock css %}

{% block app %}
<div class="ui text container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

ica/templates/management/points.html
{% extends "management/layout.html" %}

{% block content %}
<div class="ui breadcrumb">
    <a class="section" href="{{ url_for('management.index') }}">Management</a>
    <div class="divider"> / </div>
    <a class="section" href="{{ url_for('management.points') }}">Points</a>
</div>

<h3 class="ui header">Add Points</h3>
{% endblock %}